version: 2
jobs:

  build:
    macos:
      xcode: "9.0"
    steps:
      - run: yarn build
      - run: mkdir /tmp/artifacts
      - run: cp out/*.zip /tmp/artifacts

  deploy:
    macos:
      xcode: "9.0"
    steps:
      - run: yarn build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            tags:
              only: /.*/
