version: 2
jobs:
  compile:
    macos:
      xcode: '9.2.0'
    steps:
      - checkout
      - run: yarn --ignore-engines
      - run: yarn test
      - store_artifacts:
          path: dist/*

workflows:
  version: 2
  build:
    jobs:
      - compile
